# Generated by Django 5.1.6 on 2025-03-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_type', models.CharField(choices=[('month', 'MONTH'), ('year', 'YEAR'), ('week', 'WEEK'), ('day', 'Day')], default='month', max_length=255)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('features', models.ManyToManyField(to='subscriptions.feature')),
            ],
            options={
                'verbose_name_plural': 'Packages',
                'ordering': ['name'],
            },
        ),
    ]
