# Generated by Django 5.1.6 on 2025-03-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_promotioncode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotioncode',
            name='stripe_promotion_id',
        ),
        migrations.AddField(
            model_name='promotioncode',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
