# Generated by Django 5.1.6 on 2025-03-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_remove_promotioncode_stripe_promotion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='conversation_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='conversation_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(),
        ),
    ]
