# Generated by Django 5.1.6 on 2025-03-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_promotioncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncode',
            name='stripe_promotion_code_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
