# Generated by Django 5.1.6 on 2025-03-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_promotioncode_stripe_promotion_code_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
