# Generated by Django 5.1.6 on 2025-03-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_package_conversation_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
