# Generated by Django 5.1.6 on 2025-03-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_package_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromotionCode',
        ),
    ]
