# Generated by Django 5.1.6 on 2025-03-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_delete_promotioncode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.PositiveIntegerField(help_text='Enter discount percentage (0-100)')),
                ('duration', models.CharField(default='once', max_length=20)),
                ('stripe_coupon_id', models.CharField(blank=True, help_text='ID of the coupon in Stripe', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
