# Generated by Django 5.1.6 on 2025-03-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgtocode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
